apiVersion: 1

datasources:
  # Prometheus 數據源
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      timeInterval: 15s
      httpMethod: POST
    editable: true

  # Jaeger 數據源
  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686
    jsonData:
      tracesToLogs:
        datasourceUid: loki
        tags: ['job', 'instance']
        mappedTags: [{ key: 'service.name', value: 'service' }]
        mapTagNamesEnabled: true
        spanStartTimeShift: '-1h'
        spanEndTimeShift: '1h'
        filterByTraceID: true
        filterBySpanID: false
    editable: true

  # Zipkin 數據源（如果使用）
  - name: Zipkin
    type: zipkin
    access: proxy
    url: http://zipkin:9411
    jsonData:
      tracesToLogs:
        datasourceUid: loki
        tags: ['job', 'instance']
    editable: true

  # Tempo 數據源（未來可能使用）
  # - name: Tempo
  #   type: tempo
  #   access: proxy
  #   url: http://tempo:3200
  #   jsonData:
  #     tracesToLogs:
  #       datasourceUid: loki
  #     serviceMap:
  #       datasourceUid: prometheus
  #   editable: true